### ISSUE TITLE
Planning on using your source code to promote some components I've built.

### ISSUE THREAD

**Issue by cameronking4** [gonzalochale/chonza#1]
Is that ok with you? Calling it VapiBlocks fyi

**Comment by gonzalochale** [comment]
You can use it of course, I would just like some mention

**Comment by gonzalochale** [comment]
ohh I misunderstood you hahaha. You can use it of course, I would just like some mention

**Comment by cameronking4** [comment]
Appreciate it, will do thanks :)

**Comment by cameronking4** [comment]
![image](https://github.com/gonzalochale/chonza/assets/35708477/24caeeb9-be10-4645-a101-d9e9639dd0da)
Gave credit here! thanks again
